analytics-cli:
  build: .
  command: nodemon server
  ports:
    - "3000:3000"
  volumes:
    - ./:/app/analytics-cli
  links:
    - db:db


db:
  image: mysql:5.7
  volumes:
      - /conf.d/:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: tarantula
    MYSQL_DATABASE: tarantula
    MYSQL_USER: tarantula
    MYSQL_PASSWORD: tarantula
  ports:
    - "3306:3306"
  volumes:
    - ./:/app/
    - ./config/custom_mysql.cnf:/etc/mysql/conf.d/custom_mysql.cnf

